# Site settings
title: "Plumber. сайт с плеером"
url: "fj01.eu.org"
baseurl: "/"

exclude:
  - LICENSE

# pages
paginate: 10
paginate_path: "/page-:num/"

# Build settings
markdown: kramdown
permalink: /post/:title
plugins:
  - jekyll-paginate
